# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: placeholder
  stripe_publishable_key: placeholder
  stripe_secret_key: placeholder
  stripe_client_id: placeholder
  stripe_user_id: placeholder
  fee_percentage: 0.01

test:
  secret_key_base: placeholder
  stripe_publishable_key: placeholder
  stripe_secret_key: placeholder
  stripe_client_id: placeholder
  stripe_user_id: placeholder
  fee_percentage: 0.01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: placeholder
  stripe_secret_key: placeholder
  stripe_client_id: placeholder
  stripe_user_id: placeholder
  fee_percentage: 0.01

staging:
  secret_key_base: placeholder
  stripe_publishable_key: placeholder
  stripe_secret_key: placeholder
  stripe_client_id: placeholder
  stripe_user_id: placeholder
  fee_percentage: 0.01
